INSERT INTO ROLE (ID, NAME) VALUES (1, 'Admin');
INSERT INTO CATEGORY (ID, DESCRIPTION, NAME) VALUES (1, 'Ueberbetrieblicher Kurs', 'Uek');
INSERT INTO CATEGORY (ID, DESCRIPTION, NAME) VALUES (2, 'Ferien', 'Ferien');


INSERT INTO Entry (ID, CHECK_IN, CHECK_OUT, CATEGORY) VALUES (1, '2007-12-03T10:15:30', '2007-12-03T10:16:30', 1);


INSERT INTO APPLICATION_USER (ID, PASSWORD, USERNAME, ROLE) VALUES (1, '$2a$10$ESVLqsX8GLikNzPg4KxeC.HNz7AJ4H4uITVymY70c9JKfVjAev/um', 'admin', 1);
INSERT INTO APPLICATION_USER (ID, PASSWORD, USERNAME, ROLE) VALUES (2, '$2a$10$ESVLqsX8GLikNzPg4KxeC.HNz7AJ4H4uITVymY70c9JKfVjAev/um', 'testuser', null);